language: python
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- pypy
- pypy3
install: pip install -r requirements-dev.txt
script: make test-ci
after_success: coveralls -v
branches:
  only:
  - master
  - development
sudo: false
