language: python
env:
  global:
  - secure: Vblwa4W12E5+N+Ds5pK5vRFEtNNCyZMbK/jiUrI4L9Ny5KFeCm02lDq/ZR5I6CuVzzMMxIU1bO0S+C8JR4URRZZfcGFKdIpNaDm7AUdxtEUfcjMWzEvvLayr2hXr+zn37Z9cJSezqR7pfikVkr1zjqGFggJuLrL5wRsBSUK2qtk=
  - secure: ivaxrd3Duw/QiQ6+OiKXD1nq2xPIYYkow96+L/K78It6C1jkJg233l735c1vJpHh3KSTyFsMgAZMvFCefR7YOqoG1anfWjcHF8jtVTKloH/seDNAGp25DZCJTyLuUy4biOCIPKYhlmE5l8bEZOO+pApo7bNgofwO4rl4uIBVYdc=
  - secure: D8gFLnUNSX2Os4sZmfx28DdwVsLyvYpbYg43MadQrt8+TlFJYXRiXSyEcW6LemrDH+YbsyVlnvcN5zoBvkxeLbVtl8G9OjNU4q448Zti2f62zNq7Ih5y88Nx/sR84QGLr+SMelJXUr/2hJT0PhGJeNaQQCtGK0MrdlT06pdbB1c=
python:
- '2.6'
- '2.7'
- '3.3'
- '3.4'
- pypy
- pypy3
install: pip install -r requirements-dev.txt
script: make test-ci
after_success: coveralls -v
branches:
  only:
  - master
  - development
