language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
jobs:
  include:
    - python: "2.7"
      install: pip install -r requirements/test-27.txt
install: pip install -r requirements/test.txt
script: make test-ci
after_success: coveralls -v
branches:
  only:
    - master
    - development
